name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SERVER_SSH_KEY  # Укажите имя вашего окружения, где хранится SERVER_SSH_KEY
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          # Создаём директорию для SSH
          mkdir -p ~/.ssh
          # Записываем приватный ключ из секрета в файл
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          # Устанавливаем правильные права доступа
          chmod 600 ~/.ssh/id_rsa
          # Добавляем сервер в known_hosts, чтобы избежать проверки ключа хоста
          ssh-keyscan -H 82.202.139.185 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          # Подключаемся к серверу и выполняем команды
          ssh -i ~/.ssh/id_rsa user1@82.202.139.185 "
            cd /var/www/MeMap &&
            sudo git pull origin main &&
            echo 'Deployed successfully'
          "




