name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  
    environment: SERVER_SSH_KEY  # Replace with your environment name (e.g., "production")
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_IP: "82.202.139.185"
          USER: "user1"  # Замените на вашего пользователя на сервере
        run: |
          mkdir  ~/.ssh/
          chmod 700  ~/.ssh/
          echo "$PRIVATE_KEY" >  ~/.ssh/id_rsa.pub
          # chown 644 ~/.ssh/id_rsa.pub
          echo "$PRIVATE_KEY"
          ssh -o StrictHostKeyChecking=no  $USER@$SERVER_IP "
            cd /var/www/MeMap &&
            git pull origin main &&
            echo 'Deployed successfully'
          "
